codecov:
  require_ci_to_pass: yes

coverage:
  status:
    project:
      default:
        target: 0%
        threshold: 0%
        base: auto 
        flags: 
          - unit
        informational: true
  precision: 2
  round: down
  range: "0...100"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no
