version: x.x.{build}
image: Visual Studio 2019
configuration: Release
install:
- cmd: >-
    appveyor DownloadFile https://dot.net/v1/dotnet-install.ps1

    powershell -NoLogo -NoProfile -File dotnet-install.ps1 -Version 2.2.107 -InstallDir "%ProgramFiles(x86)%\dotnet" -Architecture x86
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: Iced.sln
  parallel: true
  verbosity: normal
  publish_nuget_symbols: true
  use_snupkg_format: true
before_package:
- cmd: msbuild /t:Pack /p:Configuration=Release
artifacts:
- path: Iced\bin\Release\*.*nupkg
  name: Iced NuGet Packages
test_script:
  - '"C:\Program Files\dotnet\dotnet.exe" test -c Release --no-build Iced.UnitTests\Iced.UnitTests.csproj -- RunConfiguration.NoAutoReporters=true RunConfiguration.TargetPlatform=X64'
  - '"C:\Program Files (x86)\dotnet\dotnet.exe" test -c Release --no-build Iced.UnitTests\Iced.UnitTests.csproj -- RunConfiguration.NoAutoReporters=true RunConfiguration.TargetPlatform=X86'
notifications:
- provider: Email
  to:
  - de4dot@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  on:
    APPVEYOR_REPO_TAG: true
  api_key:
    secure: en/ChGrnyp08i9CgI/8WXLKhl0OHCpPsuBSRv9wt286kvKlI9P4732egbzq+ycfx
