version: x.x.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: Iced.sln
  parallel: true
  verbosity: normal
before_package:
- cmd: dotnet pack -c Release 
artifacts:
- path: Iced\bin\Release\*.nupkg
  name: Iced NuGet Packages
test_script:
  - dotnet test -c Release Iced.UnitTests\Iced.UnitTests.csproj -- RunConfiguration.NoAutoReporters=true
notifications:
- provider: Email
  to:
  - de4dot@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false