version: x.x.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: Iced.sln
  parallel: true
  verbosity: normal
  publish_nuget_symbols: true
  use_snupkg_format: true
before_package:
- cmd: msbuild /t:Pack /p:Configuration=Release
artifacts:
- path: Iced\bin\Release\*.*nupkg
  name: Iced NuGet Packages
test_script:
  - dotnet test -c Release --no-build Iced.UnitTests\Iced.UnitTests.csproj -- RunConfiguration.NoAutoReporters=true
notifications:
- provider: Email
  to:
  - de4dot@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  on:
    APPVEYOR_REPO_TAG: true
  api_key:
    secure: en/ChGrnyp08i9CgI/8WXLKhl0OHCpPsuBSRv9wt286kvKlI9P4732egbzq+ycfx
