[package]
name = "iced-x86"
version = "0.0.0"
authors = ["0xd4d <de4dot@gmail.com>"]
license = "MIT"
description = "iced is an x86/x64 disassembler, decoder, encoder written in Rust"
homepage = "https://github.com/0xd4d/iced"
repository = "https://github.com/0xd4d/iced"
readme = "README.md"
# At most 5 keywords can be used
keywords = ["disassembler", "x86", "amd64", "x86_64", "decoder"]
categories = ["development-tools::debugging"]

[badges]
codecov = { repository = "https://github.com/0xd4d/iced", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[features]
default = ["DECODER", "ENCODER", "INSTR_INFO", "ALL_FORMATTERS", "GAS_FORMATTER",
			"INTEL_FORMATTER", "MASM_FORMATTER", "NASM_FORMATTER"]
DECODER = []
ENCODER = []
INSTR_INFO = []
ALL_FORMATTERS = []
GAS_FORMATTER = []
INTEL_FORMATTER = []
MASM_FORMATTER = []
NASM_FORMATTER = []

[dependencies]
static_assertions = "0.3.4"

[dev-dependencies]
lazy_static = "1.1.0"

[build-dependencies]
rustc_version = "0.2.3"
