[package]
name = "iced-x86-js"
version = "1.0.1"# Update html_root_url in lib.rs
authors = ["0xd4d <de4dot@gmail.com>"]
license = "MIT"
description = "iced-x86 is an x86/x64 disassembler, assembler and instruction decoder written in Rust"
homepage = "https://github.com/0xd4d/iced"
repository = "https://github.com/0xd4d/iced"
readme = "README.md"
keywords = ["disassembler", "javascript", "assembler", "x86", "amd64"]
categories = ["wasm", "development-tools::debugging", "encoding", "hardware-support"]
edition = "2018"

[lib]
# Adding "rlib" increases the wasm file size, so ... don't do it
crate-type = ["cdylib"]

[features]
default = ["decoder", "masm"]
base = ["iced-x86/std"]
instruction_api = ["base"]
decoder = ["base", "iced-x86/decoder"]
encoder = ["base", "iced-x86/encoder", "iced-x86/db"]
block_encoder = ["base", "iced-x86/block_encoder"]
op_code_info = ["base", "iced-x86/op_code_info"]
instr_info = ["base", "iced-x86/instr_info"]
gas = ["base", "iced-x86/gas"]
intel = ["base", "iced-x86/intel"]
masm = ["base", "iced-x86/masm"]
nasm = ["base", "iced-x86/nasm"]

[dependencies]
static_assertions = "1.1.0"
wasm-bindgen = "0.2.60"
js-sys = "0.3.37"

[dependencies.iced-x86]
version = "1.0.1"
path = "../iced-x86"
default-features = false

[workspace]
# We can only override [profile.release] if this is the root workspace.
# So make sure this is the root workspace.

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
